from __future__ import annotations


FAH_ONLY_FALLBACK_REASON = "low_confidence_fah_only"
FAH_ONLY_FALLBACK_MIN_MATCHES = 2
FAH_ONLY_FALLBACK_MIN_POOL_SCORE = 40.0
FAH_ONLY_FALLBACK_HG_DOMINANT_MIN_POOL_SCORE = 20.0

HG_ONLY_FALLBACK_REASON = "low_confidence_hg_only"
HG_ONLY_FALLBACK_MIN_RELATIVE_INTENSITY = 0.10

SPHINGO_HG_ONLY_FALLBACK_MIN_TOTAL_SCORE = 30.0
SPHINGO_HG_ONLY_FALLBACK_MIN_HG_SCORE = 8.0
